input {
    kb_layout = br
    kb_variant = 
    kb_model = thinkpad
    kb_options = terminate:ctrl_alt_bksp

    follow_mouse = 1

    sensitivity = 0
    accel_profile = flat

    focus_on_close = 0

    touchpad {
        natural_scroll = true
    }
}
