$mainMod = SUPER

bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, F, togglefloating,
bind = ALT, space, exec, $menu
bind = $mainMod, P, pseudo,
bind = $mainMod, J, togglesplit

#Move focus
bind = $mainMod, l, movefocus, l
bind = $mainMod, h, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

#Switch workspace
bind = $mainMod, f1, workspace, 1
bind = $mainMod, f2, workspace, 2
bind = $mainMod, f3, workspace, 3
bind = $mainMod, f4, workspace, 4
bind = $mainMod, f5, workspace, 5

#Move window to workspace
bind = $mainMod SHIFT, f1, movetoworkspace, 1
bind = $mainMod SHIFT, f2, movetoworkspace, 2
bind = $mainMod SHIFT, f3, movetoworkspace, 3
bind = $mainMod SHIFT, f4, movetoworkspace, 4
bind = $mainMod SHIFT, f5, movetoworkspace, 5

# Magic / Scratch workspace
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Move/resize window with mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
