source=~/.config/hypr/hyprland.d/99-catppuccin.conf
source=~/.config/hypr/hyprland.d/0-monitors.conf
source=~/.config/hypr/hyprland.d/0-variables.conf
source=~/.config/hypr/hyprland.d/10-general.conf
source=~/.config/hypr/hyprland.d/20-decoration.conf
source=~/.config/hypr/hyprland.d/30-animations.conf
source=~/.config/hypr/hyprland.d/40-input.conf
source=~/.config/hypr/hyprland.d/50-gestures.conf
source=~/.config/hypr/hyprland.d/60-binds.conf
source=~/.config/hypr/hyprland.d/70-rules.conf
#
